### ISSUE TITLE
Some classes does not implement async interface members

### ISSUE THREAD

**Issue by attolee** [Haruma-K/UnityScreenNavigator#19]
Enable `USN_USE_ASYNC_METHODS`, found that the following classes do not implement their interface,

1. AnonymousModalLifecycleEvent
2. AnonymousModalLifecycleEvent
3. AnonymousSheetLifecycleEvent

**Comment by Haruma-K** [comment]
@attolee 
Indeed. I will fix it.
Thanks for the info!

**Comment by Haruma-K** [comment]
@attolee 
I fixed it and released as 1.5.1!

https://github.com/Haruma-K/UnityScreenNavigator/releases/tag/1.5.1

PR is below.

https://github.com/Haruma-K/UnityScreenNavigator/pull/20

Thanks again for your information!
