### ISSUE TITLE
A Version on Nuget .org ?

### ISSUE THREAD

**Issue by hoangcuongzk1** [Haruma-K/UnityScreenNavigator#24]

**Comment by Haruma-K** [comment]
sorry, no. If you have any problems, please be specific.

**Comment by hoangcuongzk1** [comment]
> sorry, no. If you have any problems, please be specific.

I create an external library for my unity project, my lib uses .Dll code. But UnityScreenNavigator seen only support unity custom package. Can you make a version on Nuget.org ?

**Comment by Haruma-K** [comment]
Sorry I will not suport your case but you can get all files of Unity Screen Navigator so build it as you like.
