### ISSUE TITLE
Screen transitions should have an option to update in unscaled time

### ISSUE THREAD

**Issue by f1yingbanana** [Haruma-K/UnityScreenNavigator#28]
UI animations sometimes happen when `Time.timeScale` is set to 0. Animation should have an option to update in unscaled time.

For example, this could be implemented by adding a method to check whether to use scaled time in [`IUpdatable`](https://github.com/Haruma-K/UnityScreenNavigator/blob/master/Assets/UnityScreenNavigator/Runtime/Foundation/Animation/IUpdatable.cs)
 and implemented via a flag in [`TransitionAnimationObject`](https://github.com/Haruma-K/UnityScreenNavigator/blob/master/Assets/UnityScreenNavigator/Runtime/Core/Shared/TransitionAnimationObject.cs). [`UpdateDispatcher`](https://github.com/Haruma-K/UnityScreenNavigator/blob/master/Assets/UnityScreenNavigator/Runtime/Foundation/Animation/UpdateDispatcher.cs) can then pass in the time accordingly, enabling animation to play when `Time.timeScale` is 0.

**Comment by Haruma-K** [comment]
You're right. It seems correct to use UnscaledDeltaTime by default. I will fix it later.

**Comment by f1yingbanana** [comment]
Amazing framework, by the way! I wish I've found this earlier :')

**Comment by Haruma-K** [comment]
thank you, I'm grad to hear that :)

I have fixed this issue and released as version 1.6.3.

https://github.com/Haruma-K/UnityScreenNavigator/releases/tag/1.6.3
