### ISSUE TITLE
How to change data of a screens exit animation during runtime

### ISSUE THREAD

**Issue by whynames** [Haruma-K/UnityScreenNavigator#32]
How would I add custom data to exit animation of a screen during runtime? like args. For my usecase, I want screen to move towards specific dynamic object while exiting

**Comment by Haruma-K** [comment]
I have implemented an example of that case in a demo. Please take a look at it.

![Oct-11-2023 20-00-19](https://github.com/Haruma-K/UnityScreenNavigator/assets/47441314/e05c64c8-fd72-4661-82d2-77087b0b8485)
