### ISSUE TITLE
prefab_top_page.prefab was not found

### ISSUE THREAD

**Issue by seoyeon01** [Haruma-K/UnityScreenNavigator#37]
When i run the demo, get the following error

Unity 2021.3.19f1
Addressables 1.19.19

InvalidOperationException: Requested asset（Key: Top/prefab_top_page.prefab）was not found.
UnityScreenNavigator.Runtime.Core.Page.PageContainer+<PushRoutine>d__40.MoveNext () (at Assets/UnityScreenNavigator/Runtime/Core/Page/PageContainer.cs:303)
UnityScreenNavigator.Runtime.Foundation.Coroutine.CoroutineManager+<ProcessRoutine>d__12.MoveNext () (at Assets/UnityScreenNavigator/Runtime/Foundation/Coroutine/CoroutineManager.cs:107)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e8a406da998549af9a2680936c7da25a>:0)
![image](https://github.com/Haruma-K/UnityScreenNavigator/assets/48429544/ce60d597-bfb8-4e41-b13f-3ec4863dbff9)

![image](https://github.com/Haruma-K/UnityScreenNavigator/assets/48429544/6ebc3d6e-71be-408e-b633-7b79b7c3c4f8)

It's hard to understand why, 
but if i open the prefab and play while in prefab modification mode, it works.
After that, it should work fine even if i leave the prefab mode.
Is this an issue about addressables?
Is this only happening to me at the moment?

**Comment by Haruma-K** [comment]
@seoyeon01 
Sorry I fixed it!
The issue was that UnityScreenNavigatorSettings had dissapeared from PreloadedAssets. When you use this library, normally, this doesn't happen.

Thank you for your report!
