### ISSUE TITLE
How to Find Page(Modal/Sheet)?

### ISSUE THREAD

**Issue by seoyeon01** [Haruma-K/UnityScreenNavigator#38]
Is there way to find the Page(Modal / Sheet) from container(or static method way like find container)?
If it's not, is it by design reason?

For example,
(I haven't tested it in detail, so there's probably something wrong with it.)
![image](https://github.com/Haruma-K/UnityScreenNavigator/assets/48429544/b5a5f463-2489-4d8e-9e55-39f0b218f501)

duplicate pageName(Identifier) may have a problem.
But in most cases, pageName seems to be used in a unique way.

or is there a better way?
I'm wondering if there is room for this usage to cause problems.

**Comment by Haruma-K** [comment]
In an ideal scenario, you should hold onto the pageId obtained during the OnLoad at the time of a push operation and use that.

https://github.com/Haruma-K/UnityScreenNavigator/blob/a8acf7c84b70732558fbcefd2305e0ddd2126e55/Assets/UnityScreenNavigator/Runtime/Core/Page/PageContainer.cs#L190C71-L190C77

There's also an overload for Pop that allows specifying an pageId

https://github.com/Haruma-K/UnityScreenNavigator/blob/a8acf7c84b70732558fbcefd2305e0ddd2126e55/Assets/UnityScreenNavigator/Runtime/Core/Page/PageContainer.cs#L250
