### ISSUE TITLE
Description about IPageContainerCallbackReceiver

### ISSUE THREAD

**Issue by seoyeon01** [Haruma-K/UnityScreenNavigator#39]
<img width="676" alt="1" src="https://github.com/Haruma-K/UnityScreenNavigator/assets/48429544/c477581f-b4be-45b0-bd21-28431f424732">

I think GameObject of the "Container" was the intended description

++
Thank you for providing such a great project.
The articles on your blog were also very helpful :)

**Comment by Haruma-K** [comment]
You are right, i'll fix it. Thank you!

**Comment by Haruma-K** [comment]
fixed: 31b372b391d8f10e25ebb99115e584de4545d117
